version: "3.9"

services:
  co_db:
    image: postgres:16
    container_name: co_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: jwco
      POSTGRES_USER: jwco
      POSTGRES_PASSWORD: jwco_dev_pw
    ports:
      - "5433:5432"   # nach au√üen offen (pgAdmin kann drauf)
    volumes:
      - co_db_data:/var/lib/postgresql/data

volumes:
  co_db_data:
